/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public class InvertedIndex {
   
    Map<String, HashSet<String>> index = new HashMap<>();

    public void addDocument(String docId, String content){
        String[] contentSplit = content.toLowerCase().split(" ");
        for (String string : contentSplit) {
            HashSet<String> docsForWord = index.computeIfAbsent(string, key -> new HashSet<String>());
            docsForWord.add(docId);
        }
    }

    public Set<String> search(String word){
        String wordLowerCase = word.toLowerCase();
        return index.containsKey(wordLowerCase) ? index.get(wordLowerCase) : new HashSet<>();
    }

    public static void main(String[] args) {
        InvertedIndex invertedIndex = new InvertedIndex();
        
        invertedIndex.addDocument("doc1", "the cat sat");
        invertedIndex.addDocument("doc2", "the dog sat");

        System.out.println(invertedIndex.search("sat"));
        System.out.println(invertedIndex.search("cat"));
        System.out.println(invertedIndex.search("elephant"));
    }
}
