/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class InvertedIndex {

    Map<String, HashMap<String, List<Integer>>> index = new HashMap<>();

    public void addDocument(String docId, String content) {
        String[] contentSplit = content.toLowerCase().split(" ");
        for (int i = 0; i < contentSplit.length; i++) {
            HashMap<String, List<Integer>> docsForWord = index.computeIfAbsent(contentSplit[i], key -> new HashMap<String, List<Integer>>());
            docsForWord.computeIfAbsent(docId, k -> new ArrayList<>()).add(i);
        }
    }

    public Map<String, List<Integer>> search(String word) {
        String wordLowerCase = word.toLowerCase();
        return index.containsKey(wordLowerCase) ? index.get(wordLowerCase) : new HashMap<>();
    }

    public int getCount(String word) {
        int total = 0;

        String wordLowerCase = word.toLowerCase();
        Map<String, List<Integer>> getMap = search(wordLowerCase);
        for (List<Integer> positions : getMap.values()) {
            total += positions.size();
        }

        return total;
    }

    public static void main(String[] args) {
        InvertedIndex invertedIndex = new InvertedIndex();
        invertedIndex.addDocument("doc1", "the cat sat");
        invertedIndex.addDocument("doc2", "the dog sat");

        System.out.println(invertedIndex.search("sat"));
        System.out.println(invertedIndex.search("cat"));
        System.out.println(invertedIndex.search("elephant"));

        System.out.println(invertedIndex.getCount("sat"));
    }
}
