/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.Before;


public class InvertedIndexTest {

    InvertedIndex classUnderTest;
    @Before
    public void setUp(){
        classUnderTest = new InvertedIndex();
    }

    @Test 
    public void addDocument() {
        classUnderTest.addDocument("doc1", "the dog eats");
        assertTrue(classUnderTest.search("dog").contains("doc1"));
    }
}
